apiVersion: v1
kind: Service
metadata:
  name: k8s-sb
spec:
  selector:
    app: k8s-sb
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  
---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-sb
  template:
    metadata:
      labels:
        app: k8s-sb
    spec:
      containers:
        - name: app
          image: jianminlijianminli/k8s-sb:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always